services:
  redis: 
    image: redislabs/redismod
    ports:
      - '6379:6379' 
  web:
    build:
      context: ./malicious
      dockerfile: Dockerfile
    ports:
        - "8001:8001"
    volumes:
        - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis