services:
   redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379' 
   web:
    build: .
    ports:
        - "8000:8000"
    volumes:
        - .:/code
    env_file:
      - ./.env
    depends_on:
        - redis